topic_recorder:
  output_dir: ./src/topic_recorder/docs
  topics: 
    - name: /base/image_raw
      type: image
      format: mp4
      fps: 60
    - name: /outpost/image_raw
      type: image
      format: mp4
      fps: 60
    - name: /base/detector/result_img
      type: image
      format: mp4
      fps: 60
    - name: /outpost/detector/result_img
      type: image
      format: mp4
      fps: 60
