camera: hik

enable_recorder: true

odom2camera:
  # 这样写就够了，YAML 会把它当成字符串 "0.12 0.06 0.04"
  xyz: "0.12 0.06 0.04"
  rpy: "0.0 -0.0 0.0"

detector_log_level: INFO
tracker_log_level: INFO
serial_log_level: INFO
